"""v1

Revision ID: caf0835a94b8
Revises: 6dec050e6d00
Create Date: 2025-06-26 13:07:48.814875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf0835a94b8'
down_revision: Union[str, None] = '6dec050e6d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fileId', sa.String(), nullable=True),
        sa.Column('filedata', sa.LargeBinary(), nullable=True),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.Column('agentId', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('users',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('username', sa.String),
        sa.Column('hashed_password', sa.String)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.drop_table('users')
    # ### end Alembic commands ###
